### ISSUE TITLE
 Can't resolve strapi-list-zone-item

### ISSUE THREAD

**Issue by romanlex** [ExFabrica/strapi-plugin-awesome-help#1]
After install and build project have error
`Can't resolve './components/injected/strapi-list-zone-item' in '/home/wsl/Projects/@/media/node_modules/@exfabrica/strapi-plugin-awesome-help/admin/src'`

You source code have a line https://github.com/ExFabrica/strapi-plugin-awesome-help/blob/main/admin/src/index.js#L10
with wrong import path
Directory is `Injected` not `injected`

**Comment by GtaExFab** [comment]
Hi @romanlex and thanks for your feedback.
Issue is fixed on the 1.0.8 version of the plugin.
Have a good day !
